# Generated by Django 5.0.2 on 2024-03-23 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_category_news_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='Publishing_time',
            new_name='publishing_time',
        ),
    ]
